---
title: "NOK/EUR Regression"

author: "Eric Eikrem"
date: "October 2, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library("xml2")
library("dplyr")
library("ggplot2")
library("scales")
```

## NOK vs EUR Regression

```{r, results='asis'}
analysis_periods <- c(10,100,200)

nok_eur <- function(days) {
  
  url_to_read <- paste(
    "https://data.norges-bank.no/api/data/EXR/",
    "B.EUR.NOK.SP?lastNObservations=",
    days,
    sep = ""
  )
  
  nok_eur_obs <- read_xml(url_to_read) %>%
    xml_find_all("//Obs")
  
  dates_closed <- nok_eur_obs %>% 
    xml_attr("TIME_PERIOD") %>% 
    as.Date("%Y-%m-%d")
  
  nok_eur_daily <- nok_eur_obs %>% 
    xml_attr("OBS_VALUE") %>% 
    as.numeric()
  
  nok_eur_data <- data.frame(x = dates_closed, y = nok_eur_daily)
  colnames(nok_eur_data) <- c("Date", "NOK_EUR")
  nok_eur_data <- merge(nok_eur_data, nok_key_policy_rate(days), by = "Date", all = TRUE)
  
  return(nok_eur_data)
}

nok_key_policy_rate <- function(days) {
  
  url_key_policy_rates <- "https://data.norges-bank.no/api/data/IR/B.KPRA.RR.R"
  
  key_policy_rates_obs <- read_xml(url_key_policy_rates) %>%
    xml_find_all("//Obs")
  
  key_policy_rates_subset <- key_policy_rates_obs[
    (length(key_policy_rates_obs) - days + 1):length(key_policy_rates_obs)
    ]
  
  dates_closed_rates <- key_policy_rates_subset %>%
    xml_attr("TIME_PERIOD") %>%
    as.Date("%Y-%m-%d")
  
  rates_daily <- key_policy_rates_subset %>%
    xml_attr("OBS_VALUE") %>%
    as.numeric()
  
  nok_key_policy_rate_data <- data.frame(x = dates_closed_rates, y = rates_daily)
  colnames(nok_key_policy_rate_data) <- c("Date", "Key_policy_rate")
  
  for(row in 1:nrow(nok_key_policy_rate_data)){
    if(row ==1) {
      rate_change <- c(0)
    } else {
      rate_change <- c(rate_change, nok_key_policy_rate_data$Key_policy_rate[row] - nok_key_policy_rate_data$Key_policy_rate[row - 1])
    }
  }
  
  nok_key_policy_rate_data["Change"] <- rate_change
  
  return(nok_key_policy_rate_data)
  
} 

nok_eur_plot <- function(nok_eur_data, regression_method) {
  
  g <- ggplot(
      nok_eur_data, 
      aes(x = Date, y = NOK_EUR)
      ) + 
    geom_smooth(method = regression_method) +
    geom_point() + 
    labs(
      x = "Date", 
      y = paste("NOK per EUR for the last", length(nok_eur_data$NOK_EUR), "working-days", sep = " "),
      title = "NOK per EUR",
      subtitle = paste("From", min(nok_eur_data$Date), "to", max(nok_eur_data$Date), sep = " ")
      ) + 
    theme(
      axis.title.y = element_text(color = "blue")
      )
  
  rate_changes <- nok_eur_data$Change
  
  if(length(rate_changes) > 0) {
    for(i in 1:(length(rate_changes)-1)) {
      if(rate_changes[i] != 0) {
        g <- g + geom_vline(xintercept = nok_eur_data$Date[i], colour = "red", size = 1, linetype = 4)
      }
    }
  }
  plot(g)
}

for(no_days in analysis_periods) {
  
  nok_eur_plot(nok_eur(no_days), "auto")
  nok_eur_plot(nok_eur(no_days), "lm")
  
}
```

